= The Elixir Cross Referencer
:doctype: book
:pp: {plus}{plus}
:toc:
:toc-placement!:

Elixir is a source code cross-referencer inspired by
https://en.wikipedia.org/wiki/LXR_Cross_Referencer[LXR]. It's written
in Python and its main purpose is to index every release of a C or C{pp}
project (like the Linux kernel) while keeping a minimal footprint.

It uses Git as a source-code file store and Berkeley DB for cross-reference
data. Internally, it indexes Git _blobs_ rather than trees of files to avoid
duplicating work and data. It has a straightforward data structure
(reminiscent of older LXR releases) to keep queries simple and fast.

You can see it in action on https://elixir.bootlin.com/

link:CHANGELOG.adoc[Changelog]

toc::[]

= Requirements

* Git (to clone this repository)
* Docker (or a compatible container runtime)

All other dependencies (Python 3 and its libraries, Berkeley DB,
Universal Ctags, Apache) are bundled in the Docker image.

Running the test suite on a host has additional requirements, see the
_Automated testing_ section.

= Architecture

The shell script (`script.sh`) is the lower layer and provides commands
to interact with Git and other Unix utilities. The Python commands use
the shell script's services to provide access to the annotated source
code and identifier lists (`query.py`) or to create and update the
databases (`update.py`). Finally, the web interface (`web.py`) and
uses the query interface to generate HTML pages and to answer REST
queries, respectively.

When installing the system, you should test each layer manually and make
sure it works correctly before moving on to the next one.

= Installation and deployment (Docker)

The container image is used for both serving the web pages and indexing:
the `index` command, available inside the container, clones (or updates)
the git repositories and builds the databases.

== Data directory layout

Elixir keeps all its data (git repositories and databases) under a single
root directory. In the container this is `/srv/elixir-data`, with one
sub-directory per project:

----
/srv/elixir-data/
  <project 1>/
    data/
    repo/
  <project 2>/
    data/
    repo/
----

`data` holds the cross-reference databases and `repo` the bare git
repository of the project. The `index` command creates and fills these
directories, so you normally never manipulate them yourself.

== Build the Docker image

Dockerfiles are provided in the `docker/` directory.
To build the image, run the following commands:

 # git clone https://github.com/bootlin/elixir.git ./elixir
 # docker build -t elixir --build-arg ELIXIR_VERSION=`git rev-parse --short HEAD` -f ./elixir/docker/Dockerfile ./elixir

The ELIXIR_VERSION build argument is optional. Since .git directory is not copied into Docker image by default,
the option is used to pass a version string to Elixir.

== Run the container

 # mkdir ./elixir-data
 # docker run -v ./elixir-data/:/srv/elixir-data -d --name elixir-container -p 80:80 elixir

This starts Apache inside the container and serves Elixir on port 80
of the host.

== Index a project

The Docker image does not contain any repositories.
To index a repository, you can use the `index` script.
For example, to add the https://musl.libc.org/[musl] repository, run:

 # docker exec -it elixir-container index /srv/elixir-data musl

Or, to run indexing in a separate container:

 # docker run -v ./elixir-data/:/srv/elixir-data \
    --entrypoint index elixir /srv/elixir-data musl

You can also use `index /srv/elixir-data --all` to start indexing all officially supported repositories.

The `index` command fetches the project's remotes (creating the bare
repository on first run) and then runs `update.py` to build the databases.
Run it again at any time to index newly released versions.

You can set `$ELIXIR_THREADS` if you want to change the number of threads used by
update.py for indexing (by default the number of CPUs on your system).

`update.py` indexes the new tags one at a time, the oldest first, and
`utils/index` runs it after each fetch.

____
Generating the full database can take a long time: it takes about 15 hours on a Xeon E3-1245 v5 to index 1800 tags in the Linux kernel. Progress is recorded after each tag, so you can interrupt indexing and run it again later to continue where it stopped. You can even create a new Git repository and just create one tag instead of using the official kernel repository which is very large.
____

After indexing is done, Elixir should be available under the following URL on your host:
http://localhost/musl/latest/source

== Verifying the installation

The individual layers can be checked from inside the container.
`script.sh` and `utils.query` need to know which project to work on,
through the `LXR_REPO_DIR` and `LXR_DATA_DIR` environment variables:

 # docker exec \
    -e LXR_REPO_DIR=/srv/elixir-data/musl/repo \
    -e LXR_DATA_DIR=/srv/elixir-data/musl/data \
    elixir-container ./script.sh list-tags

 # docker exec \
    -e LXR_REPO_DIR=/srv/elixir-data/musl/repo \
    -e LXR_DATA_DIR=/srv/elixir-data/musl/data \
    elixir-container python3 -m utils.query ident latest malloc C

NOTE: `latest` can be replaced with any other tag, and `malloc` with any
other identifier.

Finally, check the web pages and the REST API (see below) served by
the container.

== Automatic repository updates

The Docker image does not automatically update repositories by itself.
You can, for example, start `index /srv/elixir-data --all` in the container (or in a separate container, with Elixir data volume/directory mounted)
from cron on the host to periodically update repositories and index new
releases.

== Using Docker image as a development server

You can easily use the Docker image as a development server by following the steps above, but mounting Elixir source directory from the host
into `/usr/local/elixir/` in the container when running `docker run elixir`.

Changes in the code made on the host should be automatically reflected in the container.
You can use `apache2ctl` to restart Apache.
Error logs are available in `/var/log/apache2/error.log` within the container.

= REST API usage

Once the container is running, you can test the API usage:

== ident query

Send a get request to `/api/ident/<Project>/<Ident>?version=<version>&family=<family>`.
For example:

 curl http://127.0.0.1/api/ident/barebox/cdev?version=latest&family=C

The response body is of the following structure:

----
{
    "definitions":
        [{"path": "commands/loadb.c", "line": 71, "type": "variable"}, ...],
    "references":
        [{"path": "arch/arm/boards/cm-fx6/board.c", "line": "64,64,71,72,75", "type": null}, ...]
}
----

= Maintenance and enhancements

== Using a cache to improve performance

At Bootlin, we're using the https://varnish-cache.org/[Varnish http cache]
as a front-end to reduce the load on the server running the Elixir code.

 .-------------.           .---------------.           .---------------------------.
 | Http client | --------> | Varnish cache | --------> | Elixir container (Apache) |
 '-------------'           '---------------'           '---------------------------'

= Hardware requirements

Performance requirements depend mostly on the amount of traffic that you get
on your Elixir service. However, a fast server also helps for the initial
indexing of the projects.

SSD storage is strongly recommended because of the frequent access to
git repositories.

At Bootlin, here are a few details about the server we're using:

* As of July 2019, our Elixir service consumes 17 GB of data (supporting all projects),
or for the Linux kernel alone (version 5.2 being the latest), 12 GB for indexing data,
and 2 GB for the git repository.
* We're using an LXD instance with 8 GB of RAM on a cloud server with 8 CPU cores
running at 3.1 GHz.

= Contributing to Elixir

== Supporting a new project

Elixir has a very simple modular architecture that allows to support
new source code projects by just adding a new file to the Elixir sources.

Elixir's assumptions:

* Project sources have to be available in a git repository
* All project releases are associated to a given git tag. Elixir
only considers such tags.

First make an installation of Elixir by following the above instructions
and index at least one project, to make sure it works.
See the `projects` subdirectory for projects that are already supported.

Supporting a new project requires changes in two places:

. Declare the project's git remotes: add an `add_default_remotes` line at the
end of `utils/index`, giving the project name and its remote URL(s):
+
----
add_default_remotes $1 $# $2 zephyr https://github.com/zephyrproject-rtos/zephyr
----
+
The project name *must* match the name of the file created below.

. Describe the project's tags: create a `projects/<projectname>.sh` file
(for example `projects/zephyr.sh`).

Depending on how you want to show the available versions on the Elixir pages,
you may have to apply substitutions to each tag string, for example to add
a `v` prefix if missing, for consistency with how other project versions are
shown. You may also decide to ignore specific tags. All this can be done
by redefining the default `list_tags()` function. Here's an example
(`projects/zephyr.sh` file):

 list_tags()
 {
     echo "$tags" |
         grep -v '^zephyr-v'
 }

The next step is to make sure that versions are classified as you wish
in the version menu. This classification work is done through the
`list_tags_h()` function which generates the output of the `./script.sh list-tags -h`
command. Here's what you get for the Linux project:

 v4 v4.16 v4.16
 v4 v4.16 v4.16-rc7
 v4 v4.16 v4.16-rc6
 v4 v4.16 v4.16-rc5
 v4 v4.16 v4.16-rc4
 v4 v4.16 v4.16-rc3
 v4 v4.16 v4.16-rc2
 v4 v4.16 v4.16-rc1
 ...

The first column is the top level menu entry for versions.
The second one is the next level menu entry, and
the third one is the actual version that can be selected by the menu.
Note that this third entry must correspond to the exact
name of the tag in git.

If the default behavior is not what you want, you will have
to customize the `list_tags_h` function.

You should also make sure that Elixir properly identifies
the most recent versions:

 # docker exec \
    -e LXR_REPO_DIR=/srv/elixir-data/zephyr/repo \
    -e LXR_DATA_DIR=/srv/elixir-data/zephyr/data \
    elixir-container ./script.sh get-latest-tags | head

If needed, customize the `get_latest_tags()` function.

If you want to enable support for `compatible` properties in Devicetree files,
add `dts_comp_support=1` at the beginning of `projects/<projectname>.sh`.

You are now ready to index the new project. Rebuild the Docker image
(as `utils/index` and `projects/` are copied into it), then run:

 # docker exec -it elixir-container index /srv/elixir-data zephyr

You can then check that Elixir works through the web pages served by the
container.

== Coding style

If you wish to contribute to Elixir's Python code, please
follow the https://www.python.org/dev/peps/pep-0008/[official coding style for Python].

== How to send patches

The best way to share your contributions with us is to https://github.com/bootlin/elixir/pulls[file a pull
request on GitHub].

= Automated testing

Elixir includes a test suite in `t/`.

== In a Docker container

The test suite and all its dependencies are part of the Docker image, so you
can run it without installing anything else on the host (assuming the image
was built as shown earlier):

 # docker run --rm --entrypoint prove elixir

== On the host

Running the suite on a host requires: Perl, Git, Python >= 3.8 with the
packages listed in `requirements.txt` (including `berkeleydb`, which needs
the Berkeley DB development files to build), and Universal Ctags.
From the top-level Elixir directory, run:

 prove

The test suite uses code extracted from Linux v5.4 in `t/tree`.

== Licensing of code in `t/tree`

The copied code is licensed as described in the https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/COPYING[COPYING] file included with
Linux.  All the files copied carry SPDX license identifiers of `GPL-2.0+` or
`GPL-2.0-or-later`.  Per https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility[GNU's compatibility table], GPL 2.0+ code can be used
under GPLv3 provided the combination is under GPLv3.  Moreover, https://www.gnu.org/licenses/license-list.en.html#AGPLv3.0[GNU's overview
of AGPLv3] indicates that its terms "effectively consist of the terms of GPLv3"
plus the network-use paragraph.  Therefore, the developers have a good-faith
belief that licensing these files under AGPLv3 is authorized.  (See also https://github.com/Freemius/wordpress-sdk/issues/166#issuecomment-310561976[this
issue comment] for another example of a similar situation.)

= License

Elixir is copyright (c) 2017--2020 its contributors.  It is licensed AGPLv3.
See the `COPYING` file included with Elixir for details.
